services:
  # Frontend: React (Static Site)
  - type: web
    name: resume-analyzer-ui
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false # This tells Render to keep the value you set in the dashboard
